global:
  # These will be injected by skaffold
  # image: consul
  # imageK8S: consul-k8s-control-plane
  name: consul
  datacenter: dc1
  enablePodSecurityPolicies: false
  # tls:
  #   enabled: true
  # acls:
  #   manageSystemACLs: true
  experiments: ["resource-apis"] # v2 APIs
server:
  replicas: 1
ui:
  enabled: false
  port:
    http: 80
    https: 443
  service:
    type: 'ClusterIP'
connectInject:
  default: true
  # mirroringK8S: true
  # envoyExtraArgs: "--log-level trace"
  transparentProxy:
    defaultEnabled: true
controller:
  enabled: true
# syncCatalog:
#   enabled: true
# terminatingGateways:
#   enabled: true
